require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MtgDbCardsController do

  # This should return the minimal set of attributes required to create a valid
  # MtgDbCard. As you add validations to MtgDbCard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MtgDbCardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mtg_db_cards as @mtg_db_cards" do
      mtg_db_card = MtgDbCard.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mtg_db_cards).should eq([mtg_db_card])
    end
  end

  describe "GET show" do
    it "assigns the requested mtg_db_card as @mtg_db_card" do
      mtg_db_card = MtgDbCard.create! valid_attributes
      get :show, {:id => mtg_db_card.to_param}, valid_session
      assigns(:mtg_db_card).should eq(mtg_db_card)
    end
  end

  describe "GET new" do
    it "assigns a new mtg_db_card as @mtg_db_card" do
      get :new, {}, valid_session
      assigns(:mtg_db_card).should be_a_new(MtgDbCard)
    end
  end

  describe "GET edit" do
    it "assigns the requested mtg_db_card as @mtg_db_card" do
      mtg_db_card = MtgDbCard.create! valid_attributes
      get :edit, {:id => mtg_db_card.to_param}, valid_session
      assigns(:mtg_db_card).should eq(mtg_db_card)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MtgDbCard" do
        expect {
          post :create, {:mtg_db_card => valid_attributes}, valid_session
        }.to change(MtgDbCard, :count).by(1)
      end

      it "assigns a newly created mtg_db_card as @mtg_db_card" do
        post :create, {:mtg_db_card => valid_attributes}, valid_session
        assigns(:mtg_db_card).should be_a(MtgDbCard)
        assigns(:mtg_db_card).should be_persisted
      end

      it "redirects to the created mtg_db_card" do
        post :create, {:mtg_db_card => valid_attributes}, valid_session
        response.should redirect_to(MtgDbCard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mtg_db_card as @mtg_db_card" do
        # Trigger the behavior that occurs when invalid params are submitted
        MtgDbCard.any_instance.stub(:save).and_return(false)
        post :create, {:mtg_db_card => {  }}, valid_session
        assigns(:mtg_db_card).should be_a_new(MtgDbCard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MtgDbCard.any_instance.stub(:save).and_return(false)
        post :create, {:mtg_db_card => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mtg_db_card" do
        mtg_db_card = MtgDbCard.create! valid_attributes
        # Assuming there are no other mtg_db_cards in the database, this
        # specifies that the MtgDbCard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MtgDbCard.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => mtg_db_card.to_param, :mtg_db_card => { "these" => "params" }}, valid_session
      end

      it "assigns the requested mtg_db_card as @mtg_db_card" do
        mtg_db_card = MtgDbCard.create! valid_attributes
        put :update, {:id => mtg_db_card.to_param, :mtg_db_card => valid_attributes}, valid_session
        assigns(:mtg_db_card).should eq(mtg_db_card)
      end

      it "redirects to the mtg_db_card" do
        mtg_db_card = MtgDbCard.create! valid_attributes
        put :update, {:id => mtg_db_card.to_param, :mtg_db_card => valid_attributes}, valid_session
        response.should redirect_to(mtg_db_card)
      end
    end

    describe "with invalid params" do
      it "assigns the mtg_db_card as @mtg_db_card" do
        mtg_db_card = MtgDbCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MtgDbCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => mtg_db_card.to_param, :mtg_db_card => {  }}, valid_session
        assigns(:mtg_db_card).should eq(mtg_db_card)
      end

      it "re-renders the 'edit' template" do
        mtg_db_card = MtgDbCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MtgDbCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => mtg_db_card.to_param, :mtg_db_card => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mtg_db_card" do
      mtg_db_card = MtgDbCard.create! valid_attributes
      expect {
        delete :destroy, {:id => mtg_db_card.to_param}, valid_session
      }.to change(MtgDbCard, :count).by(-1)
    end

    it "redirects to the mtg_db_cards list" do
      mtg_db_card = MtgDbCard.create! valid_attributes
      delete :destroy, {:id => mtg_db_card.to_param}, valid_session
      response.should redirect_to(mtg_db_cards_url)
    end
  end

end
